site_name: EICRUD - Documentation
theme:
  logo: planet.svg
  favicon: planet.svg
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - content.code.copy
    - navigation.footer
    - content.tabs.link

plugins:
  - search
  - awesome-pages

copyright: "contact@eicrud.com"

extra:
  homepage: https://example.com
  social:
    - icon: fontawesome/brands/discord
      link: https://example.com
      name: discord
    - icon: fontawesome/solid/heart
      link: https://example.com
      name: support this project
    - icon: fontawesome/brands/github
      link: https://example.com
      name: source code        
    - icon: fontawesome/solid/earth-europe
      link: https://example.com
      name: homepage    

repo_url: https://github.com/eicrud/eicrud

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: false
      pygments_style: 'dracula'
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - toc:
      toc_depth: 2
      title: On this page
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
 